#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Fabian Schmieder
#
# Generate every package definition from the release artifacts.
#
# Three definitions come from this one script:
#   packaging/devserial.rb            Homebrew, four hosts, measured checksums
#   packaging/devserial-bin/PKGBUILD  AUR, installs the released binary
#   packaging/devserial/PKGBUILD      AUR, builds from the tagged sources
#
# Hand-maintained copies of the same facts drifted apart before: the PKGBUILD
# pointed at a tag that never existed, unpacked a directory that never existed
# and declared 'SKIP' instead of a checksum, while the formula lived as a
# heredoc inside the release workflow and covered macOS only.
#
# Usage:
#   package-metadata.sh --version 1.2.3 --tag devserial-v1.2.3 \
#                       --artifact-dir dist --output-dir packaging \
#                       [--base-url https://github.com/OWNER/REPO/releases/download]

set -euo pipefail

PACKAGE=devserial
# In CI this is the repository the workflow runs in, so a rename cannot leave
# the package sources pointing at a redirect.
REPOSITORY=${GITHUB_REPOSITORY:-metaneutrons/devserial}
DESCRIPTION='MCP server bridging serial hardware to LLMs via SQLite-backed buffer'
HOMEPAGE="https://github.com/${REPOSITORY}"
LICENSE_ID='GPL-3.0-or-later'

version=''
tag=''
artifact_dir=''
output_dir=''
base_url=''

die() {
  echo "package-metadata: $*" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version) version=$2; shift 2 ;;
    --tag) tag=$2; shift 2 ;;
    --artifact-dir) artifact_dir=$2; shift 2 ;;
    --output-dir) output_dir=$2; shift 2 ;;
    --base-url) base_url=$2; shift 2 ;;
    *) die "unknown argument '$1'" ;;
  esac
done

[[ -n "$version" ]] || die 'missing --version'
[[ -n "$tag" ]] || die 'missing --tag'
[[ -n "$artifact_dir" ]] || die 'missing --artifact-dir'
[[ -n "$output_dir" ]] || die 'missing --output-dir'
[[ -d "$artifact_dir" ]] || die "artifact directory '$artifact_dir' does not exist"
: "${base_url:=${HOMEPAGE}/releases/download}"

mkdir -p "$output_dir"

# Targets that end up in a package. Windows and musl are released but are not
# consumed by Homebrew or the AUR.
TARGETS=(
  aarch64-apple-darwin
  x86_64-apple-darwin
  aarch64-unknown-linux-gnu
  x86_64-unknown-linux-gnu
)

archive_name() {
  echo "${PACKAGE}-${version}-$1.tar.gz"
}

archive_path() {
  local name
  name=$(archive_name "$1")
  # The archives may sit directly in the directory or in a per-target
  # subdirectory, which is how downloaded workflow artifacts arrive.
  local found
  found=$(find "$artifact_dir" -type f -name "$name" -print -quit)
  [[ -n "$found" ]] || die "archive '$name' not found under '$artifact_dir'"
  echo "$found"
}

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  else
    shasum -a 256 "$1" | cut -d' ' -f1
  fi
}

declare -A SHA
for target in "${TARGETS[@]}"; do
  SHA["$target"]=$(sha256_of "$(archive_path "$target")")
done

url_for() {
  echo "${base_url}/${tag}/$(archive_name "$1")"
}

# ------------------------------------------------------------------ Homebrew

formula="${output_dir}/${PACKAGE}.rb"
cat > "$formula" <<FORMULA
# Generated by scripts/release/package-metadata.sh. Do not edit by hand.
class Devserial < Formula
  desc "${DESCRIPTION}"
  homepage "${HOMEPAGE}"
  license "${LICENSE_ID}"
  # No explicit version: Homebrew scans it from the archive name, and
  # 'brew audit --strict' rejects the redundant declaration.

  on_macos do
    if Hardware::CPU.arm?
      url "$(url_for aarch64-apple-darwin)"
      sha256 "${SHA[aarch64-apple-darwin]}"
    else
      url "$(url_for x86_64-apple-darwin)"
      sha256 "${SHA[x86_64-apple-darwin]}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "$(url_for aarch64-unknown-linux-gnu)"
      sha256 "${SHA[aarch64-unknown-linux-gnu]}"
    else
      url "$(url_for x86_64-unknown-linux-gnu)"
      sha256 "${SHA[x86_64-unknown-linux-gnu]}"
    end
  end

  def install
    bin.install "${PACKAGE}"
    # The binary embeds font software; its notices have to travel with it.
    doc.install "THIRD-PARTY-NOTICES.md", "licenses"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/${PACKAGE} --version")
    assert_match "Available Serial Hardware", shell_output("#{bin}/${PACKAGE} list")
  end
end
FORMULA

# ----------------------------------------------------------------------- AUR

mkdir -p "${output_dir}/${PACKAGE}-bin"
pkgbuild="${output_dir}/${PACKAGE}-bin/PKGBUILD"
cat > "$pkgbuild" <<PKGBUILD
# Generated by scripts/release/package-metadata.sh. Do not edit by hand.
# Maintainer: metaneutrons <https://github.com/metaneutrons>
pkgname=${PACKAGE}-bin
pkgver=${version}
pkgrel=1
pkgdesc='${DESCRIPTION}'
arch=('x86_64' 'aarch64')
url='${HOMEPAGE}'
license=('${LICENSE_ID}')
depends=('glibc' 'gcc-libs')
provides=('${PACKAGE}')
conflicts=('${PACKAGE}')
options=('!strip')
source_x86_64=('$(url_for x86_64-unknown-linux-gnu)')
sha256sums_x86_64=('${SHA[x86_64-unknown-linux-gnu]}')
source_aarch64=('$(url_for aarch64-unknown-linux-gnu)')
sha256sums_aarch64=('${SHA[aarch64-unknown-linux-gnu]}')

package() {
  # The installed binary keeps the plain name, because that is what users type
  # and what the archive contains. The licence and documentation directories
  # follow \$pkgname, which is Arch convention and here also keeps this package
  # from claiming paths that belong to the source package it conflicts with.
  install -Dm755 "\$srcdir/${PACKAGE}" "\$pkgdir/usr/bin/${PACKAGE}"
  install -Dm644 "\$srcdir/LICENSE" "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE"
  install -Dm644 "\$srcdir/README.md" "\$pkgdir/usr/share/doc/\$pkgname/README.md"
  # The binary embeds font software; its notices have to travel with it.
  install -Dm644 "\$srcdir/THIRD-PARTY-NOTICES.md" \\
    "\$pkgdir/usr/share/licenses/\$pkgname/THIRD-PARTY-NOTICES.md"
  install -Dm644 -t "\$pkgdir/usr/share/licenses/\$pkgname/" "\$srcdir"/licenses/*.txt
}
PKGBUILD

# ------------------------------------------------------- AUR, from source

# The source package clones the tag rather than a generated tarball. GitHub
# does not guarantee that its archive endpoint produces the same bytes over
# time, and a changed checksum breaks the package for everyone.
mkdir -p "${output_dir}/${PACKAGE}"
source_pkgbuild="${output_dir}/${PACKAGE}/PKGBUILD"
cat > "$source_pkgbuild" <<SOURCEPKGBUILD
# Generated by scripts/release/package-metadata.sh. Do not edit by hand.
# Maintainer: metaneutrons <https://github.com/metaneutrons>
pkgname=${PACKAGE}
pkgver=${version}
pkgrel=1
pkgdesc='${DESCRIPTION}'
arch=('x86_64' 'aarch64')
url='${HOMEPAGE}'
license=('${LICENSE_ID}')
# Loaded at run time by the GUI. Confirm with namcap after a real build.
depends=('gcc-libs' 'glibc' 'libxkbcommon' 'libx11' 'wayland' 'libgl')
makedepends=('cargo' 'git' 'libxcb')
conflicts=('${PACKAGE}-bin')
# makepkg.conf ships OPTIONS=(... lto) and LTOFLAGS="-flto=auto", and cc-rs
# picks CFLAGS up from the environment. The bundled sqlite3 then compiles to
# LLVM bitcode, rustc links the resulting archive without an LTO plugin, and
# every sqlite3 symbol comes out undefined. That failure is on record from the
# pipeline run against devserial-v0.1.4-pipelinetest.2; disabling LTO is the
# usual remedy for a Rust package with a vendored C library. The archlinux
# image only runs emulated on the maintainer machine, so the fix itself is
# proven by the next pipeline run rather than locally.
options=('!lto')
source=("\${pkgname}::git+${HOMEPAGE}.git#tag=${tag}")
sha256sums=('SKIP')

prepare() {
  cd "\$pkgname"
  export RUSTUP_TOOLCHAIN=stable
  cargo fetch --locked --target "\$(rustc -vV | sed -n 's/host: //p')"
}

build() {
  cd "\$pkgname"
  export RUSTUP_TOOLCHAIN=stable
  export CARGO_TARGET_DIR=target
  cargo build --frozen --release --all-features
}

check() {
  cd "\$pkgname"
  export RUSTUP_TOOLCHAIN=stable
  cargo test --frozen --all-features
}

package() {
  cd "\$pkgname"
  install -Dm755 "target/release/\$pkgname" "\$pkgdir/usr/bin/\$pkgname"
  install -Dm644 LICENSE "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE"
  install -Dm644 README.md "\$pkgdir/usr/share/doc/\$pkgname/README.md"
  # The binary embeds font software; its notices have to travel with it.
  install -Dm644 THIRD-PARTY-NOTICES.md \\
    "\$pkgdir/usr/share/licenses/\$pkgname/THIRD-PARTY-NOTICES.md"
  install -Dm644 -t "\$pkgdir/usr/share/licenses/\$pkgname/" licenses/*.txt
}
SOURCEPKGBUILD

# ------------------------------------------------------------------- report

echo "wrote ${formula}"
echo "wrote ${pkgbuild}"
echo "wrote ${source_pkgbuild}"
for target in "${TARGETS[@]}"; do
  printf '  %-28s %s\n' "$target" "${SHA[$target]}"
done
